### ISSUE TITLE
Abstracting color nomenclature

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-base#20]
Discussions around future proofing and theming led to the need of reducing things like "red" and "blue" to more abstract ideas like "destructive" and "primary"

~

[changing existing things]  -->  **[to these things]**

~

calcite-ui-blue  -->  **calcite-ui-blue-1**
calcite-ui-blue-hover  -->  **calcite-ui-blue-2**
calcite-ui-blue-press  -->  **calcite-ui-blue-3**
calcite-ui-green  -->  **calcite-ui-green-1**
calcite-ui-green-hover  -->  **calcite-ui-green-2**
calcite-ui-green-press  -->  **calcite-ui-green-3**
calcite-ui-yellow  -->  **calcite-ui-yellow-1**
calcite-ui-yellow-hover  -->  **calcite-ui-yellow-2**
calcite-ui-yellow-press  -->  **calcite-ui-yellow-3**
calcite-ui-red  -->  **calcite-ui-red-1**
calcite-ui-red-hover  -->  **calcite-ui-red-2**
calcite-ui-red-press  -->  **calcite-ui-red-3**
calcite-ui-background  -->  no change
calcite-ui-foreground  -->  **calcite-ui-foreground-1**
calcite-ui-foreground-hover  -->  **calcite-ui-foreground-2**
calcite-ui-foreground-press  -->  **calcite-ui-foreground-3**
calcite-ui-text-1  -->  no change
calcite-ui-text-2  -->  no change
calcite-ui-text-3  -->  no change
calcite-ui-border-1  -->  no change
calcite-ui-border-2  -->  no change
calcite-ui-border-3  -->  no change
calcite-ui-border-hover  -->  **calcite-ui-border-4**
calcite-ui-border-press  -->  **calcite-ui-border-5**

**Comment by bstifle** [comment]
not sure if we need to rename calcite-ui-border-hover and calcite-ui-border-press.

open to suggestions on anything

**Comment by macandcheese** [comment]
Since hover and press are just darker versions of border 1-2-3, seems weird that we'd break that naming. Even though they aren't sequentially stepped I still think it makes sense to use 4-5 there.

I like the idea of more "intentful" prescriptive naming, at least for component attributes, but you run into issues with it meaning different things in different places if you rename the underlying variables.

For instance a red toggle means "destructive", a red input message icon might mean "invalid", and a red alert means "error".  A blue alert might mean "info or general" but, a blue button is just a "primary" (this also breaks when you try to apply primary/scondary/tertiary/quaternary to white / black buttons - that's totally up to an app to decide once you reach a certain "depth" of order).

Keeping the underlying variables as the actual colors makes them more general and applicable, which I think is good at a low-level.

I'd be for changing Calcite Component to intent based attributes in certain places - intent="in

**Comment by macandcheese** [comment]
Re: theming - I think that's valid but perhaps just for spot colors, I think we could still provide flexibility to users while ensuring that ... warning doesn't equal purple, and success isn't red, etc.

**Comment by bstifle** [comment]
ok so are you proposing only changing blue to primary?

i could see green or even a yellow as the primary, in that case green and yellow variables start falling apart

is the main issue calling it destructive for red?

what if we go even more abstract

Blue --> Primary
Green --> Good
Yellow --> Not so good
Red --> Bad

**Comment by macandcheese** [comment]
I don't think we should change any of the underlying colors at this low of a level. Maybe at the calcite-component variable level. I think it's kind of unnecessary abstraction here though, I'd imagine when we approach theming we'll want to allow "brand spot" colors that override at the component level. This is mostly just for developers of Calcite Components to use (and other Esri properties), so I think leaving blue as blue, etc., makes sense here, for now.

**Comment by bstifle** [comment]
thats fine with me. @julio8a ?

**Comment by julio8a** [comment]
Yeah, I'm good with that.

**Comment by bstifle** [comment]
ok the original post was updated accordingly
